INSERT INTO Accounts ("FIRST_NAME","SURNAME","ACCOUNT_NUMBER") VALUES ('John', 'Doe', '1234');
INSERT INTO Accounts ("FIRST_NAME","SURNAME","ACCOUNT_NUMBER") VALUES ('Jane','Doe','1235');
INSERT INTO Accounts ("FIRST_NAME","SURNAME","ACCOUNT_NUMBER") VALUES ('Jim','Taylor','1236');